Script started on Wed 24 Feb 2021 04:41:29 AM EST
tuser@tutor-vserver:~/hw1_part2$ scp ivana86@users.cs.umb.edu:cs444/hw1_part2/tesstio.* .
ivana86@users.cs.umb.edu's password: 
testio.c                                        0%    0     0.0KB/s   --:-- ETAtestio.c                                      100% 3170     3.1KB/s   00:00    
testio.lnx                                      0%    0     0.0KB/s   --:-- ETAtestio.lnx                                    100%   46KB  45.6KB/s   00:01    
testio.o                                        0%    0     0.0KB/s   --:-- ETAtestio.o                                      100% 8808     8.6KB/s   00:00    
testio.syms                                     0%    0     0.0KB/s   --:-- ETAtestio.syms                                   100% 2155     2.1KB/s   00:00    
tuser@tutor-vserver:~/hw1_part2$ scp ivana86@users.cs.umb.edu:cs444/hw1_part2/tesstio.* .[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cls[K
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cmtip -f testio.lnx
For command help, type ~?
For help on args, rerun without args
Code starts at 0x100100
Using board # 1 
Please type <CR> to confirm console setting: 
Setting console dev to COM2Console: colour EGA+ 80x25
COM1 at 0x03f8 (irq = 4) is a 16550A
COM2 at 0x02f8 (irq = 3) is a 16550A

                 Welcome to UMB Tutor for the PC
   UMB Tutor is a 32-bit protected-mode PC debugger/downloader,
       based on Linux, UMB Tutor for m68k, and remote gdb.
UMB Tutor is free software and you are welcome to distribute copies
of it under certain conditions.  There is no warranty for this program.
The copyright and warranty provisions follow the Gnu general public
license, available for view in gdb and elsewhere.  Full sources available.
--bugs, suggestions, questions to eoneil@cs.umb.edu

Exception 3 at EIP=00057a9b: Breakpoint
Tutor> ~downloading testio.lnx

...........Done.

Download done, setting EIP to 100100.
Tutor> g o  o 100100
Running with device TTY1

Trying simple write(4 chars)...
hi!
write of 4 returned 4
<doing delay>
Trying longer write (9 chars)
abcdefghiwrite of 9 returned 9
<doing delay>

Trying write of 80-char string...
AABBCCDDEEFFGGHHIIJJKKLLMMNNOOPPQQRRSSTTUUVVWWXXYYZZ[[\\]]^^__``aabbccddeeffgghh
write returned 80
<doing delay>

Type 10 chars input to test typeahead while looping for delay...
<doing delay>
qazwsxedfg
Got 10 chars into buf. Trying write of buf...
qazwsxedfg
Trying another 10 chars read right away...
jklfhurhfj
Got 10 chars on second read
jklfhurhfj

Now turning echo off--

Type 20 chars input, note lack of echoes...
<doing delay>

Trying write of buf...
rfskjhufoncjflcjfjss
Asked for 20 characters; got 20
Exception 3 at EIP=00100110: Breakpoint
Tutor> md 300000
00300000    2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a ****************
Tutor> 
00300010    2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a ****************
Tutor> 
00300020    2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a ****************
Tutor> 
00300030    2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a ****************
Tutor> 
00300040    2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a ****************
Tutor> 
00300050    2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a ****************
Tutor> 
00300060    2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a ****************
Tutor> 
00300070    2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a ****************
Tutor> 
00300080    2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a ****************
Tutor> 
00300090    2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a ****************
Tutor> 
003000a0    2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 2a 00 00 00 *************...
Tutor> 
003000b0    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
Tutor> 
003000c0    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
Tutor> 
003000d0    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
Tutor> 
003000e0    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
Tutor> 
003000f0    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
Tutor> 
00300100    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
Tutor> 
Tutor> 
Quit handler: 
killing process 2182 Leaving board #1
tuser@tutor-vserver:~/hw1_part2$ exit
exit

Script done on Wed 24 Feb 2021 04:44:06 AM EST
